### ISSUE TITLE
Offset?

### ISSUE THREAD

**Issue by ColeTownsend** [benschwarz/am-grid#5]
In the default flex box grid there is an offset built in. Is there a reason it didn't translate here?

**Comment by benschwarz** [comment]
@ColeTownsend I don't often use offsets and decided to omit them. 

I'd be 100% happy to accept a change that added offsets, we were just super time limited getting `am` out the door when I released `am-grid`.

**Comment by ColeTownsend** [comment]
I'll copy it over using the same principals you did, it shouldn't be hard or conflict.

**Comment by benschwarz** [comment]
Sounds great @ColeTownsend !
